import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BillingInfo from "./component/billinginfo";
import CarCard from "./component/carcard";
import ConfirmationCode from "./component/confirmation";
import PaymentMethod from "./component/paymethod";
import RentalSummary from "./component/rentalsumm";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BillingInfo/>
        <CarCard/>
        <ConfirmationCode/>
        <PaymentMethod/>
        <RentalSummary/>
        {children}
      </body>
    </html>
  );
}
